version: '3'
services:
  rabbitmq:
    image: "delayed-rabbitmq-management-final-demo"
    restart: always
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
